import Head from 'next/head'
import Image from 'next/image'
import Contact from '../components/Contact'
import Expirence from '../components/Expirence'
import Footer from '../components/Footer'
import Intro from '../components/Intro'
import Navbar from '../components/Navbar'
import Portfolio from '../components/Portfolio'
import Services from '../components/Services'
import Testimonials from '../components/Testimonials'
import Works from '../components/Works'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Subhabrata Majee</title>
        <meta name="description" content="Generated by create next app" />
<script async src="https://www.googletagmanager.com/gtag/js?id=G-67M983DQ8G"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-67M983DQ8G');
</script>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro />
      <Services />
      <Expirence />
      <Works />
      <Portfolio />
      <Testimonials />
      <Contact />
      {/* <Footer /> */}
    </div>
  )
}
